# inputs:
#   url - the url of the video to process
#   bpm - the bpm to stretch and slice the video at
#   segments - int of total segments to divide by
outputs:
  segmentList: ${split.segmentList}
  downloadName: ${download.path.name}
  table: ${init.table}
  name: ${download.path.name}
jobs:
  init:
    task: "initVideoTable"
  download:
    task: "download"
    dependsOn: [init]
    inputs:
      url: ${inputs.url}
      table: ${init.table}
  duration:
    task: "videoDuration"
    dependsOn: [download]
    inputs:
      file: ${download.filePath}  
  snap:
    task: "snapBPM"
    dependsOn: [duration]
    inputs:
      BPM: ${inputs.bpm}
      duration: ${duration.duration}  
  stretch:
    task: "stretchVideo"
    dependsOn: [snap]
    inputs:
      table: ${init.table}
      file: ${download.filePath}
      durationFrom: ${duration.duration}
      durationTo: ${snap.closestDuration}      
  segment_length:
    task: "segmentsLength"
    dependsOn: [snap]
    inputs:
      duration: ${snap.closestDuration}
      segments: ${snap.beats}  
  split:
    task: "splitVideoSegments"
    dependsOn: [segment_length, stretch]
    inputs:
      table: ${init.table}
      file: ${stretch.file}
      segments: ${snap.beats}
      segmentDuration: ${segment_length.segmentDuration}