name: BPM Splice
inputs:
  url: ''
  bpm: 120
  divide: 1
jobs:
  init:
    job: "initVideoTable"
  download:
    job: "download"
    dependsOn: [init]
    inputs:
      url: ${inputs.url}
      table: ${init.table}
  video_info:
    job: "getVideoInfo"
    dependsOn: [download]
    inputs:
      file: ${download.filePath}  
  snap:
    job: "snapBPM"
    dependsOn: [video_info]
    inputs:
      BPM: ${inputs.bpm}
      duration: ${video_info.duration}
      divide: ${inputs.divide}
  stretch:
    job: "stretchVideo"
    dependsOn: [snap]
    inputs:
      table: ${init.table}
      file: ${download.filePath}
      durationFrom: ${video_info.duration}
      durationTo: ${snap.closestDuration}      
  segment_length:
    job: "segmentsLength"
    dependsOn: [snap]
    inputs:
      duration: ${snap.closestDuration}
      segments: ${snap.segments}  
  split:
    job: "splitVideoSegments"
    dependsOn: [segment_length, stretch]
    inputs:
      table: ${init.table}
      file: ${stretch.file}
      segments: ${snap.segments}
      segmentDuration: ${segment_length.segmentDuration}

outputs:
  segmentList: ${split.segmentList}
  downloadName: ${download.path.name}
  table: ${init.table}
  name: ${download.path.name}
