name: BPM Splice
inputs:
  url:
    label: Url
    default: https://interwebdev.b-cdn.net/708edcfc-05aa-44a0-b98b-39601f451553_result8a23031ad1942baf_chf3.mp4
  bpm: 
    label: BPM
    default: 120
  divide: 
    label: Divide by
    default: 1
jobs:
  init:
    job: "initVideoTable"
  download:
    job: "download"
    dependsOn: [init]
    inputs:
      url: ${inputs.url}
      table: ${init.table}
  video_info:
    job: "getVideoInfo"
    dependsOn: [download]
    inputs:
      file: ${download.filePath}  
  snap:
    job: "snapBPM"
    dependsOn: [video_info]
    inputs:
      BPM: ${inputs.bpm}
      duration: ${video_info.duration}
      divide: ${inputs.divide}
  stretch:
    job: "stretchVideoDuration"
    dependsOn: [snap]
    inputs:
      table: ${init.table}
      file: ${download.filePath}
      durationFrom: ${video_info.duration}
      durationTo: ${snap.closestDuration}      
  segment_length:
    job: "eval"
    dependsOn: [snap]
    inputs:
      code: ${snap.closestDuration} / ${snap.segments}      
  split:
    job: "splitVideoSegments"
    dependsOn: [segment_length, stretch]
    inputs:
      table: ${init.table}
      file: ${stretch.file}
      segments: ${snap.segments}
      segmentDuration: ${segment_length.result}

outputs:
  segmentList: ${split.segmentFiles}
  downloadName: ${download.path.name}
  table: ${init.table}
  name: ${download.path.name}
