name: Combine Videos
description: Simple combine

inputs:
  url_a:
    label: Video URL 1
    default: https://interwebdev.b-cdn.net/708edcfc-05aa-44a0-b98b-39601f451553_result8a23031ad1942baf_chf3.mp4
  url_b:
    label: Video URL 2
    default: https://interwebdev.b-cdn.net/dbf13f08-2435-419a-bb7e-4c1280af794a_result86387234df48fd05_chf3.mp4
  alpha:
    label: Percent of transparency, between 0 and 1
    default: 0.5  

jobs:
  init:
    job: "initVideoTable"
  download_a:
    job: "download"
    dependsOn: [init]
    inputs:
      url: ${inputs.url_a}
      table: ${init.table}
  download_b:
    job: "download"
    dependsOn: [init]
    inputs:
      url: ${inputs.url_b}
      table: ${init.table}      
  video_info:
    job: "getVideoInfo"
    dependsOn: [download_a]
    inputs:
      file: ${download_a.file}
  combine:
    job: "overlayVideos"
    dependsOn: [video_info, download_b]
    inputs:
      top: 0
      left: 0
      start: 0
      end: ${video_info.duration}
      alpha: ${inputs.alpha}
      file_a: ${download_a.file}
      file_b: ${download_b.file}

outputs:
  fadedFile: ${combine.file}