name: Fade in w/ color
description: Simple fade

inputs:
  url:
    label: Video URL
    default: ./table/d-0d75169687528b6ccc77233a37604d87-p84656-s1.mp4
  color:    
    label: Color to fade
    default: black
  type:
    label: Fade type
    default: fade
  duration:
    label: Duration of fade in seconds
    default: 1

jobs:
  init:
    job: "initVideoTable"
  download:
    job: "download"
    dependsOn: [init]
    inputs:
      url: ${inputs.url}
      table: ${init.table}
  video_info:
    job: "getVideoInfo"
    dependsOn: [download]
    inputs:
      file: ${download.file}
  solidVideo:
    job: "createSolidVideo"
    dependsOn: [video_info]
    inputs:
      table: ${init.table}
      color: ${inputs.color}
      width: ${video_info.width}
      height: ${video_info.height}
      duration: ${inputs.duration}
      rate: ${video_info.rate}
  fade:
    job: "fadeVideos"
    dependsOn: [solidVideo]
    inputs:
      file_a: ${download.file}
      file_b: ${solidVideo.file}
      type: ${inputs.type}
      start: 0
      duration: ${inputs.duration}

outputs:
  fadedFile: ${fade.file}