jobs:
  init:
    task: "init"
  download_a:
    task: "download"
    dependsOn: [init]
    inputs:
      url: https://interwebdev.b-cdn.net/708edcfc-05aa-44a0-b98b-39601f451553_result8a23031ad1942baf_chf3.mp4
      table: ${init.table}
  download_b:
    task: "download"
    dependsOn: [init]
    inputs:
      url: https://interwebdev.b-cdn.net/a73417b9-0f91-494c-ae30-3b9e9c9b4db6_resultf5205f08514befa7_chf3.mp4
      table: ${init.table}