name: Weave x2
description: Creates a single video from splicing 2 videos in at a specific BPM
inputs:
  bpm:
    label: BPM
    default: 110
  divide:
    label: Divide segment duration by
    default: 1
  url_a:    
    label: First Video URL
    default: https://interwebdev.b-cdn.net/708edcfc-05aa-44a0-b98b-39601f451553_result8a23031ad1942baf_chf3.mp4
  url_b:    
    label: Second Video URL
    default: https://interwebdev.b-cdn.net/a73417b9-0f91-494c-ae30-3b9e9c9b4db6_resultf5205f08514befa7_chf3.mp4

jobs:
  bpm_splice_a:
    job: runWorkflow
    workflowPath: ./flows/bpm-splice.yaml
    inputs:      
      url: ${inputs.url_a}
      bpm: ${inputs.bpm}
      divide: ${inputs.divide}
  bpm_splice_b:
    job: runWorkflow
    workflowPath: ./flows/bpm-splice.yaml
    inputs:
      url: ${inputs.url_b}
      bpm: ${inputs.bpm}
      divide: ${inputs.divide}
  shuffle_ab:
    job: shuffleX
    dependsOn: [bpm_splice_a, bpm_splice_b]
    inputs:
      shuffleList:
        - ${bpm_splice_a.segmentList}
        - ${bpm_splice_b.segmentList}
  write_list_ab:
    job: writeList
    dependsOn: [shuffle_ab]
    inputs:
      list: ${shuffle_ab.shuffled}
  merge_ab:
    job: combineVideos
    dependsOn: [write_list_ab]
    inputs:
      listFile: ${write_list_ab.listFile}
      table: ${bpm_splice_a.table}
  clean_a:
    job: cleanTable
    dependsOn: [merge_ab]
    inputs:
      table: ${bpm_splice_a.table}
      prefix: ${bpm_splice_a.name}
  clean_b:
    job: cleanTable
    dependsOn: [merge_ab]
    inputs:
      table: ${bpm_splice_b.table}
      prefix: ${bpm_splice_b.name}      

outputs:
  file: ${merge_ab.merged}