jobs:
  init:
    task: "initVideoTable"
  download_a:
    task: "download"
    dependsOn: [init]
    inputs:
      url: https://interwebdev.b-cdn.net/708edcfc-05aa-44a0-b98b-39601f451553_result8a23031ad1942baf_chf3.mp4
      table: ${init.table}
  download_b:
    task: "download"
    dependsOn: [init]
    inputs:
      url: https://interwebdev.b-cdn.net/a73417b9-0f91-494c-ae30-3b9e9c9b4db6_resultf5205f08514befa7_chf3.mp4
      table: ${init.table}
  duration_a:
    task: "videoDuration"
    dependsOn: [download_a]
    inputs:
      file: ${download_a.filePath}
  duration_b:
    task: "videoDuration"
    dependsOn: [download_b]
    inputs:
      file: ${download_b.filePath}
  snap_a:
    task: "snapBPM"
    dependsOn: [duration_a]
    inputs:
      BPM: 150
      duration: ${duration_a.duration}
  snap_b:
    task: "snapBPM"
    dependsOn: [duration_b]
    inputs:
      BPM: 150
      duration: ${duration_b.duration}
  stretch_a:
    task: "stretchVideo"
    dependsOn: [snap_a]
    inputs:
      file: ${download_a.filePath}
      durationFrom: ${duration_a.duration}
      durationTo: ${snap_a.closestDuration}
  stretch_b:
    task: "stretchVideo"
    dependsOn: [snap_b]
    inputs:
      file: ${download_b.filePath}
      durationFrom: ${duration_b.duration}
      durationTo: ${snap_b.closestDuration}
  segment_length_a:
    task: "segmentsLength"
    dependsOn: [snap_a]
    inputs:
      duration: ${snap_a.closestDuration}
      segments: ${snap_a.beats}
  segment_length_b:
    task: "segmentsLength"
    dependsOn: [snap_b]
    inputs:
      duration: ${snap_b.closestDuration}
      segments: ${snap_b.beats}
  split_a:
    task: "splitVideoSegments"
    dependsOn: [segment_length_a, stretch_a]
    inputs:
      file: ${stretch_a.file}
      segments: ${snap_a.beats}
      segmentDuration: ${segment_length_a.segmentDuration}
  split_b:
    task: "splitVideoSegments"
    dependsOn: [segment_length_b, stretch_b]
    inputs:
      file: ${stretch_b.file}
      segments: ${snap_b.beats}
      segmentDuration: ${segment_length_b.segmentDuration}
  shuffle_ab:
    task: "shuffleX"
    dependsOn: [split_a, split_b]
    inputs:
      shuffleList:
        - ${split_a.segmentList}
        - ${split_b.segmentList}
  write_list_ab:
    task: "writeList"
    dependsOn: [shuffle_ab]
    inputs:
      list: ${shuffle_ab.shuffled}

  merge_ab:
    task: "combineVideos"
    dependsOn: [write_list_ab]
    inputs:
      listFile: ${write_list_ab.listFile}